const papers=[
{id:1,title:'Data Structures & Algorithms — Semester Test',subject:'DSA',exam:'B.Tech CSE',year:2026,marks:80,duration:'3 hours',difficulty:'Medium',topics:['Arrays','Linked Lists','Trees','Graphs']},
{id:2,title:'Class 10 Mathematics — Board Practice Paper',subject:'Mathematics',exam:'Class 10',year:2026,marks:80,duration:'3 hours',difficulty:'Balanced',topics:['Algebra','Geometry','Trigonometry']},
{id:3,title:'Python Programming — End Semester',subject:'Python',exam:'BCA',year:2025,marks:70,duration:'2.5 hours',difficulty:'Medium',topics:['Loops','Functions','OOP','Lists']},
{id:4,title:'SQL & Database Systems — University Paper',subject:'SQL',exam:'B.Tech CSE',year:2025,marks:60,duration:'2 hours',difficulty:'Hard',topics:['Joins','Normalization','Queries']},
{id:5,title:'Data Structures — Previous Year Paper',subject:'DSA',exam:'B.Tech CSE',year:2024,marks:80,duration:'3 hours',difficulty:'Hard',topics:['Stacks','Queues','Trees','Sorting']},
{id:6,title:'Class 10 Mathematics — Previous Year',subject:'Mathematics',exam:'Class 10',year:2024,marks:80,duration:'3 hours',difficulty:'Medium',topics:['Algebra','Statistics','Probability']}
];
const questions=[
{id:101,subject:'DSA',topic:'Linked Lists',difficulty:'Medium',marks:5,text:'Write an algorithm to reverse a singly linked list.',source:'DSA Semester Test 2026',answer:'Use three pointers: previous, current and next. Reverse each next link while traversing.'},
{id:102,subject:'DSA',topic:'Trees',difficulty:'Easy',marks:3,text:'What is the maximum number of nodes at level k in a binary tree?',source:'Data Structures 2024',answer:'2^k when the root is at level 0.'},
{id:103,subject:'DSA',topic:'Sorting',difficulty:'Hard',marks:6,text:'Compare merge sort and quicksort for worst-case time and auxiliary space.',source:'Data Structures 2024',answer:'Merge sort is O(n log n) worst-case with O(n) auxiliary space; classic quicksort is O(n²) worst-case with O(log n) expected stack space.'},
{id:104,subject:'Mathematics',topic:'Algebra',difficulty:'Medium',marks:4,text:'If x + 1/x = 5, find x² + 1/x².',source:'Class 10 Mathematics 2026',answer:'Square both sides: x² + 2 + 1/x² = 25, so the answer is 23.'},
{id:105,subject:'Mathematics',topic:'Probability',difficulty:'Easy',marks:2,text:'A fair die is thrown once. What is the probability of getting an even number?',source:'Class 10 Mathematics 2024',answer:'There are 3 even outcomes out of 6, so 1/2.'},
{id:106,subject:'Python',topic:'Functions',difficulty:'Easy',marks:3,text:'What is the purpose of the return statement in a Python function?',source:'Python End Semester 2025',answer:'It sends a value back to the caller and ends the function execution.'},
{id:107,subject:'Python',topic:'OOP',difficulty:'Medium',marks:5,text:'Explain the difference between a class and an object with a simple Python example.',source:'Python End Semester 2025',answer:'A class is a blueprint; an object is an instance created from that blueprint.'},
{id:108,subject:'SQL',topic:'Joins',difficulty:'Medium',marks:5,text:'Write a query conceptually describing how to list all customers even when they have no orders.',source:'SQL University Paper 2025',answer:'Use a LEFT JOIN from Customers to Orders on the customer key.'},
{id:109,subject:'SQL',topic:'Normalization',difficulty:'Hard',marks:6,text:'Explain how partial dependency violates Second Normal Form.',source:'SQL University Paper 2025',answer:'In a relation with a composite key, a non-key attribute depending on only part of that key is a partial dependency and violates 2NF.'},
{id:110,subject:'DSA',topic:'Graphs',difficulty:'Medium',marks:5,text:'State one key difference between BFS and DFS and name their usual auxiliary data structures.',source:'DSA Semester Test 2026',answer:'BFS explores level-by-level using a queue; DFS explores depth-first using a stack or recursion.'}
];
const mcqs=[
{subject:'DSA',difficulty:'Easy',q:'Which structure does BFS normally use?',options:['Stack','Queue','Heap','Hash table'],correct:1,explain:'Breadth-first search processes vertices level by level with a queue.'},
{subject:'DSA',difficulty:'Medium',q:'Which traversal of a BST gives keys in sorted order?',options:['Preorder','Inorder','Postorder','Level order'],correct:1,explain:'Inorder traversal of a binary search tree visits keys in ascending order.'},
{subject:'Mathematics',difficulty:'Easy',q:'What is 15% of 200?',options:['15','20','30','40'],correct:2,explain:'0.15 × 200 = 30.'},
{subject:'Python',difficulty:'Easy',q:'Which keyword defines a function in Python?',options:['func','define','def','function'],correct:2,explain:'Python uses the def keyword.'},
{subject:'SQL',difficulty:'Medium',q:'Which join keeps every row from the left table?',options:['INNER JOIN','LEFT JOIN','CROSS JOIN','SELF JOIN'],correct:1,explain:'LEFT JOIN retains all rows from the left table.'}
];

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function route(){const id=(location.hash||'#home').slice(1);$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('.main-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${id}`));$('#mainNav').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});}
window.addEventListener('hashchange',route);route();
$('#menuBtn').onclick=()=>$('#mainNav').classList.toggle('open');

function paperCard(p){return `<article class="paper-card"><div class="meta"><span class="tag">${p.subject}</span><span class="tag">${p.year}</span><span class="tag">${p.difficulty}</span></div><h3>${p.title}</h3><p>${p.exam} • ${p.marks} marks • ${p.duration}</p><p>${p.topics.join(' · ')}</p><div class="paper-actions"><button onclick="openPaper(${p.id})">View & use</button><button onclick="remixPaper(${p.id})">Remix</button><button onclick="startPaperPractice(${p.id})">Practice</button></div></article>`}
function renderPapers(list=papers){$('#paperList').innerHTML=list.map(paperCard).join('')||'<div class="empty-state">No matching papers.</div>'}
$('#recentPapers').innerHTML=papers.slice(0,3).map(paperCard).join('');
const subjects=[...new Set([...papers.map(p=>p.subject),...questions.map(q=>q.subject)])];
subjects.forEach(s=>{$('#subjectFilter').insertAdjacentHTML('beforeend',`<option>${s}</option>`);$('#practiceSubject').insertAdjacentHTML('beforeend',`<option>${s}</option>`);$('#newSubject').insertAdjacentHTML('beforeend',`<option>${s}</option>`)});
[...new Set(papers.map(p=>p.year))].sort((a,b)=>b-a).forEach(y=>$('#yearFilter').insertAdjacentHTML('beforeend',`<option>${y}</option>`));
renderPapers();
function filterPapers(){const term=$('#paperSearch').value.toLowerCase(),sub=$('#subjectFilter').value,year=$('#yearFilter').value;renderPapers(papers.filter(p=>(!term||JSON.stringify(p).toLowerCase().includes(term))&&(!sub||p.subject===sub)&&(!year||String(p.year)===year)))}
['paperSearch','subjectFilter','yearFilter'].forEach(id=>$('#'+id).addEventListener(id==='paperSearch'?'input':'change',filterPapers));

function renderQuestions(){const term=$('#questionSearch').value.toLowerCase(),diff=$('#difficultyFilter').value;const list=questions.filter(q=>(!term||JSON.stringify(q).toLowerCase().includes(term))&&(!diff||q.difficulty===diff));$('#questionList').innerHTML=list.map(q=>`<article class="question-card"><div><div class="question-meta"><span class="tag">${q.subject}</span><span class="tag">${q.topic}</span><span class="tag">${q.difficulty}</span><span class="tag">${q.marks} marks</span></div><h3>${q.text}</h3><p>Source: ${q.source}</p></div><div class="question-actions"><button onclick="showAnswer(${q.id})">Answer</button><button onclick="addToPaper(${q.id})">+ Paper</button></div></article>`).join('')||'<div class="empty-state">No matching questions.</div>'}
$('#questionSearch').oninput=renderQuestions;$('#difficultyFilter').onchange=renderQuestions;renderQuestions();

function openModal(html){$('#modalBody').innerHTML=html;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false')}
function closeModal(){$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true')}
$('#modalClose').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
window.openPaper=id=>{const p=papers.find(x=>x.id===id);openModal(`<span class="eyebrow">PAPER WORKSPACE</span><h2>${p.title}</h2><p>${p.exam} • ${p.year} • ${p.marks} marks • ${p.duration}</p><div class="analysis-card"><h3>Quick analysis</h3><p><strong>Topics:</strong> ${p.topics.join(', ')}</p><p><strong>Difficulty:</strong> ${p.difficulty}</p><p>This sample shows how one archived paper can become many learning activities.</p></div><div class="modal-tools"><button>View paper</button><button>Download PDF</button><button onclick="startPaperPractice(${p.id})">Solve online</button><button>See solutions</button><button onclick="remixPaper(${p.id})">Create similar</button><button>Analyse trends</button></div>`)};
window.showAnswer=id=>{const q=questions.find(x=>x.id===id);openModal(`<span class="eyebrow">ANSWER & EXPLANATION</span><h2>${q.text}</h2><p>${q.answer}</p><p><strong>Source:</strong> ${q.source}</p>`)};
window.addToPaper=id=>openModal('<h2>Added to paper draft</h2><p>This demo action represents adding the selected question to a teacher’s working paper.</p>');
window.remixPaper=id=>{const p=papers.find(x=>x.id===id);location.hash='create';$('#newSubject').value=p.subject;$('#newTitle').value=`${p.subject} — Remix of ${p.year} paper`;$('#newMethod').value='Remix old papers'};
window.startPaperPractice=id=>{const p=papers.find(x=>x.id===id);location.hash='practice';if(subjects.includes(p.subject))$('#practiceSubject').value=p.subject;buildPractice()};

let practicePool=[],practiceIndex=0,score=0,attempted=0;
function buildPractice(){const sub=$('#practiceSubject').value,diff=$('#practiceDifficulty').value;practicePool=mcqs.filter(x=>(!sub||x.subject===sub)&&(!diff||x.difficulty===diff));if(!practicePool.length)practicePool=mcqs.filter(x=>x.subject===sub);practiceIndex=0;score=0;attempted=0;renderPractice()}
function renderPractice(){const q=practicePool[practiceIndex%practicePool.length];$('#practiceScore').textContent=`${score} / ${attempted}`;if(!q){$('#practiceCard').innerHTML='<div class="empty-state">No sample MCQs for this filter.</div>';return}$('#practiceCard').innerHTML=`<span class="eyebrow">QUESTION ${practiceIndex+1}</span><h2>${q.q}</h2><div>${q.options.map((o,i)=>`<button class="answer" data-answer="${i}">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div><div id="practiceExplain"></div>`;$$('.answer').forEach(b=>b.onclick=()=>answerPractice(Number(b.dataset.answer)))}
function answerPractice(choice){const q=practicePool[practiceIndex%practicePool.length];attempted++;if(choice===q.correct)score++;$$('.answer').forEach((b,i)=>{b.disabled=true;if(i===q.correct)b.classList.add('correct');else if(i===choice)b.classList.add('wrong')});$('#practiceExplain').innerHTML=`<div class="explanation"><strong>${choice===q.correct?'Correct':'Review this one'}</strong><p>${q.explain}</p><button class="btn primary" id="nextPractice">Next Question</button></div>`;$('#practiceScore').textContent=`${score} / ${attempted}`;$('#nextPractice').onclick=()=>{practiceIndex++;renderPractice()}}
$('#newPractice').onclick=buildPractice;$('#practiceSubject').onchange=buildPractice;$('#practiceDifficulty').onchange=buildPractice;buildPractice();

$('#paperForm').onsubmit=e=>{e.preventDefault();const sub=$('#newSubject').value,total=Number($('#newMarks').value),level=$('#newDifficulty').value;let pool=questions.filter(q=>q.subject===sub);if(level!=='Balanced')pool=pool.filter(q=>q.difficulty===level).concat(pool.filter(q=>q.difficulty!==level));let picked=[],sum=0,i=0;while(sum<total&&i<pool.length*4){const q=pool[i%pool.length];if(sum+q.marks<=total)picked.push(q),sum+=q.marks;i++}$('#generatedPaper').innerHTML=`<span class="eyebrow">GENERATED SAMPLE</span><h2>${$('#newTitle').value}</h2><p><strong>${sub}</strong> • Target ${total} marks • ${level} • ${$('#newMethod').value}</p>${picked.map((q,n)=>`<div class="paper-question"><strong>Q${n+1}. (${q.marks} marks)</strong> ${q.text}<br><small>${q.topic} • ${q.difficulty}</small></div>`).join('')}<div class="explanation"><strong>Validation</strong><p>Generated ${sum}/${total} marks from available demo questions. A production system would fill exact blueprints from the full question bank.</p></div><div class="hero-actions"><button class="btn secondary">Print</button><button class="btn secondary">Export PDF</button><button class="btn primary" onclick="demoPublish()">Publish Online Test</button></div>`};
window.demoPublish=()=>openModal('<h2>Online test ready</h2><p>In the complete system this creates a shareable exam URL, timer, answer sheet and automatic result dashboard.</p>');

function studentDashboard(){return `<div class="dashboard-grid"><article class="metric-card"><strong>72%</strong><span>Average score</span></article><article class="metric-card"><strong>18</strong><span>Papers attempted</span></article><article class="metric-card"><strong>146</strong><span>Questions solved</span></article><article class="metric-card"><strong>6h 40m</strong><span>Practice time</span></article></div><div class="dashboard-lower"><article class="analysis-card"><h3>Topic performance</h3><table><tr><th>Topic</th><th>Progress</th><th>Score</th></tr><tr><td>Arrays</td><td><div class="bar"><i style="width:88%"></i></div></td><td>88%</td></tr><tr><td>Linked Lists</td><td><div class="bar"><i style="width:72%"></i></div></td><td>72%</td></tr><tr><td>Trees</td><td><div class="bar"><i style="width:49%"></i></div></td><td>49%</td></tr><tr><td>Graphs</td><td><div class="bar"><i style="width:40%"></i></div></td><td>40%</td></tr></table></article><article class="analysis-card"><h3>Recommended next</h3><p><strong>Graph Traversal Practice</strong></p><p>Your weakest recent topic is Graphs. Try a 10-question focused set.</p><a class="btn primary" href="#practice">Practice weak topic</a></article></div>`}
function teacherDashboard(){return `<div class="dashboard-grid"><article class="metric-card"><strong>3,840</strong><span>Questions</span></article><article class="metric-card"><strong>84</strong><span>My papers</span></article><article class="metric-card"><strong>32</strong><span>Tests conducted</span></article><article class="metric-card"><strong>186</strong><span>Students</span></article></div><div class="dashboard-lower"><article class="analysis-card"><h3>Recent tests</h3><table><tr><th>Test</th><th>Students</th><th>Average</th></tr><tr><td>DSA Mock 3</td><td>42</td><td>68%</td></tr><tr><td>Python Functions</td><td>35</td><td>77%</td></tr><tr><td>SQL Joins</td><td>29</td><td>64%</td></tr></table></article><article class="analysis-card"><h3>Quick actions</h3><p>Create a paper, upload an old exam, add a question or review results.</p><a class="btn primary" href="#create">Create paper</a></article></div>`}
function renderDashboard(role='student'){$('#dashboardContent').innerHTML=role==='student'?studentDashboard():teacherDashboard()}
$$('[data-role]').forEach(b=>b.onclick=()=>{$$('[data-role]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderDashboard(b.dataset.role)});renderDashboard();

$('#globalSearchBtn').onclick=()=>{const t=$('#globalSearch').value;location.hash='papers';$('#paperSearch').value=t;filterPapers()};$$('[data-search]').forEach(b=>b.onclick=()=>{$('#globalSearch').value=b.dataset.search;$('#globalSearchBtn').click()});
$('#uploadDemo').onclick=()=>openModal('<span class="eyebrow">UPLOAD CENTRE</span><h2>Upload → Extract → Review → Publish</h2><p>The production version can accept PDF, image, DOCX, text, CSV or JSON and convert paper content into reusable question records.</p><div class="modal-tools"><button>Choose PDF</button><button>Choose image</button><button>Import JSON</button></div>');
$$('[data-demo="mock"]').forEach(b=>b.onclick=()=>openModal(`<span class="eyebrow">MOCK EXAM PREVIEW</span><div class="mock-screen"><div class="mock-top"><span>DSA Mock Test</span><span>59:42 remaining</span></div><h2>Question 4 of 20</h2><p>Which traversal of a binary search tree returns values in sorted order?</p><label><input type="radio" name="m"> Preorder</label><br><label><input type="radio" name="m"> Inorder</label><br><label><input type="radio" name="m"> Postorder</label><br><br><button class="btn primary">Save & Next</button></div>`));

let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));